### ISSUE TITLE
Application Spacewarp

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#10]
I see that this project was not setup on top of the ASW fork. Was there a specific reason for this? Do you see any potential issues in migrating this project on top of the ASW fork?

**Comment by AlexThiv** [comment]
You should be able to use the ASW fork to use in Gloveball. There will be some artefacts to look out for that will need to be address if you toggle ASW on.

There are some visual artefacts that results from using ASW, here are some we noticed when we tested it out:
* Fast rotations impact the motion vector and creates weird visual artefacts.
* This is noticeable when throwing balls as well as the spectators waving the flags.
