### ISSUE TITLE
Hand tracking blocking plane

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#11]
In the Oculus Interaction SDK there is the function to stop the ghost hand mesh passing through the mesh of buttons and UI using the surface plane. Is there a way to implement this for Avatars hands too?

**Comment by jasonmeisel** [comment]
There is! The Avatars in this project are using a body tracking class that forwards the hands/controllers from OVRInput. What you want is to use a body tracking class that forwards the SyntheticHands from ISDK.

For reference, that's how the [rig is set up in Decommissioned](https://github.com/oculus-samples/Unity-Decommissioned/blob/main/Assets/Decommissioned/Prefabs/UIItems/GameControl/CameraRig.prefab). You can see the body tracking classes [here](https://github.com/oculus-samples/Unity-Decommissioned/tree/main/Assets/Decommissioned/Scripts/Avatars/Scripts).

The feature you're referring to specifically is called [Touch Limiting](https://developer.oculus.com/documentation/unity/unity-isdk-poke-interaction/#poke-touch-limiting-with-hands). It's not currently used in Decommissioned, but if you add the `HandPokeInteractorVisual` component to the rig, it should work.

**Comment by owlandfox** [comment]
Excellent thanks I will try this out
