### ISSUE TITLE
Passthrough styler error on v53.1

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#12]
On updating to v53.1 this error occurs -

Assets\Oculus\SampleFramework\Usage\Passthrough\Scripts\PassthroughStyler.cs(33,13): error CS0246: The type or namespace name 'OVRPassthroughColorLut' could not be found (are you missing a using directive or an assembly reference?)

Looks like its related to the new LUT passthrough feature but not sure how to reolve this as Ive just importeed a whole clean package in so not sure why there is an error on this.

**Comment by AlexThiv** [comment]
Hi @owlandfox,
Looks like you might have gotten the latest Integration SDK from the [download page](https://developer.oculus.com/downloads/package/unity-integration/). Part of this package is the Meta XR utilities which in this project is taken from a UPM package. As of v53 packages can mostly be taken from UPM.

In your case you could update the Meta XR Utilities package to use v53 through the package manager and that will solve your issue.
