### ISSUE TITLE
Updating to v56

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#15]
Currently trying to update to oculus SDK v56 as we want to implement some Movement SDK features. On upgrading the v56 asset we get some errors with Photon Realtime Transport for Netcode for GameObjects. 

![image](https://github.com/oculus-samples/Unity-UltimateGloveBall/assets/15714783/892e1b15-12ea-4ef6-969a-3497d842e090)

Not sure how to update this or if even updating it will solve anything?

**Comment by jasonmeisel** [comment]
This is an issue in the Photon Transport package here: https://github.com/Unity-Technologies/multiplayer-community-contributions/issues/230

The issue has to be fixed in that package. I'm not sure how it's related to Oculus v56, though.

**Comment by WoodsFiend** [comment]
Not sure if this functions yet as I am just spinning up new project, but it does eliminate the error. Find the photon asmdef file that is throwing the error "com.community.netcode.transport.photon-realtime" which is in /Packages. Add Unity.Collections as an Assembly Definition Reference and apply.

**Comment by owlandfox** [comment]
OK this works fine thanks. In the process as we are now well into v58 in standard Integration and v60 in new UPM manager I attempted to upgrade the SDK to v57 and now getting a whole bunch of new errors - 
![image](https://github.com/oculus-samples/Unity-UltimateGloveBall/assets/15714783/62300c6b-62e2-48ae-bd06-86acc48cd0d7)

Hopefully the repo gets updated to v60 UPM manager version because this is just getting crazy now

**Comment by owlandfox** [comment]
I can confirm that downloading a tarball for Oculus utlities v57 legacy and installing manually via browser fixes the above bugs. But would still like to request that the project is converted to work with new UPM packages going forward to ensure compatability with regular updates from Meta.

**Comment by AlexThiv** [comment]
We updated the project to use SDK v60 on Unity 2021.3.26f1.

We hope this helps you move forward. If you encounter any issues please open a new issue!
