### ISSUE TITLE
Stuck on "Loading..." screen

### ISSUE THREAD

**Issue by jayohTM** [oculus-samples/Unity-UltimateGloveBall#16]
Hi there, I am attempting to test the project on my Quest 3. I've been able to build and push to my device, but it gets hung up on the logo/splash/loading screen (shown below). 

![29e5a5f2dca894a4d01c50ae079493ea](https://github.com/oculus-samples/Unity-UltimateGloveBall/assets/462210/a6219b61-69b9-4b3b-902e-778a1a8e7cc3)

The only info from the logs that may be related are: 

> 2023/10/22 11:29:51.236 6629 6663 Fatal libc Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 6663 (UnityMain), pid 6629 (timategloveball)

Any suggestions?

**Comment by jasonmeisel** [comment]
Could you provide us with the following:

1. Unity version
2. Full log from the run
3. APK file that crashes

**Comment by WoodsFiend** [comment]
This looks like the same issue I was having, I had those same unhelpful logs. Check logcat, if you find an error that says "You are not entitled to use this app" then it is the same issue. 

You have to complete the entire setup in the docs and you must use the same account on your headset that is used for the meta developer account. If you want to use a different account you need to upload a build to meta and add the user to the release channel.

**Comment by jasonmeisel** [comment]
Thanks for the bug report, but without the requested info, we will not be able to diagnose it. Feel free to open a new issue with that info.
