### ISSUE TITLE
Unable to join user invite

### ISSUE THREAD

**Issue by Banupriyan** [oculus-samples/Unity-UltimateGloveBall#18]
With the new software update of Quest 2 labeled version 60.0.0.214.366, I'm unable to join invite from my friend. In the previous version everything worked as expected. When I try to join from the quest2 notifications dashboard, it pop ups the following error "Location is not joinable right now".

**Comment by AlexThiv** [comment]
We are investigating the issue, thanks for reporting it.

**Comment by AlexThiv** [comment]
@Banupriyan do you still run into this issue?
If you do can you make sure that both users are in the developer orgs when testing the application?

**Comment by AlexThiv** [comment]
We haven't been able to reproduce it in latest OS version. I will close it, if you run into that issue please reopen it.
