### ISSUE TITLE
Invalid Deeplink Message JSON values in the Documentation cause exception

### ISSUE THREAD

**Issue by masammut** [oculus-samples/Unity-UltimateGloveBall#2]
The Deeplink Message values provided in the [Configuration documentation](https://github.com/oculus-samples/Unity-UltimateGloveBall/blob/main/Documentation/Configuration.md) use invalid json.

This causes the following exception at runtime (and the game does not start):

- ArgumentException: JSON parse error: Missing a name for object member.

at line 91, in file PlayerPresenceHandler.cs:

- var msg = JsonUtility.FromJson<ArenaDeepLinkMessage>(destination.DeeplinkMessage);

The issue is that the values provided in the documentation use a double quote symbol of “ rather than the json valid ".

**Comment by AlexThiv** [comment]
Thanks @masammut for pointing this out. We fixed the documentation to use the appropriate type of quotation mark.
