### ISSUE TITLE
Errors on Install

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#5]
Downloaded the repo and opened up the startup scene and got multiple popups and error consoles for missing packages and dependencies even though it looks like everything is there in the project - 
![image](https://user-images.githubusercontent.com/15714783/229343153-062b7832-f899-4b90-b967-0134fb79a8de.png)

**Comment by owlandfox** [comment]
![image](https://user-images.githubusercontent.com/15714783/229910339-08e9da20-3442-487a-b4e4-d185a8f1fc12.png)

**Comment by owlandfox** [comment]
Attempted to remove and reinstall all custom packages from git as they were showing red error icons next to all of them - 
![image](https://user-images.githubusercontent.com/15714783/229917234-7aba4810-5d78-409e-b1b6-8a92e3c9a9d5.png)

But still no joy. Didnt seem to fix anything?

**Comment by AlexThiv** [comment]
Hi @owlandfox,

We are sorry you ran into this issue. There was an issue with our npm registry which prevented you from downloading the com.meta.xr.sdk.utilities package. This is now resolve and you will be able to open the project without errors.

If you don't have any issue you can close this.

**Comment by owlandfox** [comment]
OK that worked! Only issue is now the startup scene wont transition to the next screen. Seems to be stuck on the loading screen. All the correct info and settings have been added to the app in Oculus developer centre.

**Comment by AlexThiv** [comment]
Have you also created the Photon application and set the photon appId? [Photon Configuration](https://github.com/oculus-samples/Unity-UltimateGloveBall/blob/main/Documentation/Configuration.md#photon-configuration)

Another possibility is that it doesn't detect you as being entitled, check the logs on startup for any errors. You might need to go on the product page and get the application to get it to start.

**Comment by owlandfox** [comment]
Yep, Photons all good. OK Ill push out a release build to the production channel and grab it from the product page. Just to confirm this project will work for both Quest standalone and Quest Link right? We ideally want to target both. I realise we would need to setup a separate Rift app in the portal for this but when changing build targets from Android to Windows in editor I get a red message popping up that build target must be Android?

**Comment by AlexThiv** [comment]
It works using link as this is one of the main way we have been iterating on it in editor for the gameplay.
There is some features that are not implemented to work when using link like the Invite and Roster panels as this was targeted for Quest. We don't guaranty that all features work on link as we didn't spend time verifying it. But with some modifications you should be able to update it to your liking. Overall the main gameplay functionalities work while using Link.

This will work cross platform if you use the same photon appId for all platforms.

The red error was mainly to get people attention on changing their build target.
I will close this issue as we are now on a different topic.
