### ISSUE TITLE
Ray Examples scene broken on device

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#6]
We are using the canvas ray interactable functionality from interaction SDK in our project to interact with UI. 

On standalone device the Ray functionality is broken as can be seen on the Ray examples scene. Rays and camera work fine if facing forward but as soon as head is moved left, right, up or down camera freezes. Strangely it seems to be affected by the guardian boundary. If I step slightly outside the boundary so that it appears on the ground the camera does not freeze. But if I am safely inside the boundary and it is faded out then camera freezes on movement. This only occurs in ray scene. All others appear fine and this was not happening in v49

**Comment by AlexThiv** [comment]
For this specific issue I would recommend posting in the forum here https://communityforums.atmeta.com/t5/Developer/ct-p/developer

Closing as this is beyond the scope of this project.
